modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
[[mods]]
modId="spawnbalanceutility"
version="${file.jarVersion}"
displayName="SpawnBalanceUtility"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spawn-balance-utility"
updateJSONURL="https://github.com/mactso/SpawnBalanceUtility/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Spawn Balance Utility.'
[[dependencies.spawnbalanceutility]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.spawnbalanceutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17.0)"
    ordering="NONE"
    side="SERVER"


